apiVersion: v1
kind: Service
metadata:
  name: monitor-service
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: monitor-service
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
