apiVersion: v1
kind: ServiceAccount
metadata:
  name: pulsarops-sa
  namespace: pulsarops
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pulsarops-role
  namespace: pulsarops
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pulsarops-rolebinding
  namespace: pulsarops
subjects:
  - kind: ServiceAccount
    name: pulsarops-sa
    namespace: pulsarops
roleRef:
  kind: Role
  name: pulsarops-role
  apiGroup: rbac.authorization.k8s.io
