global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: api-gateway
    metrics_path: /metrics
    static_configs:
      - targets:
          - api-gateway:8000

  - job_name: monitor-service
    metrics_path: /metrics
    static_configs:
      - targets:
          - monitor-service:8000

  - job_name: alert-service
    metrics_path: /metrics
    static_configs:
      - targets:
          - alert-service:8000
