input {
  beats {
    port => 5044
  }

  tcp {
    port => 5000
    codec => json
  }
}

filter {
  if [service] == "api-gateway" or [service] == "monitor-service" or [service] == "alert-service" {
    mutate {
      add_field => { "[@metadata][index]" => "pulsarops-%{[service]}-%{+YYYY.MM.dd}" }
    }
  }

  if [level] {
    mutate {
      uppercase => [ "level" ]
    }
  }

  date {
    match => [ "time", "ISO8601" ]
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "%{[@metadata][index]}"
  }

  stdout {
    codec => rubydebug
  }
}
